name: Build and Test QuoteMachine

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    name: Run .NET Tests ✅
    runs-on: windows-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🧰 Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: 📦 Restore dependencies
      run: dotnet restore QuoteMachine-ExerciceGit.sln

    - name: 🛠️ Build solution
      run: dotnet build QuoteMachine-ExerciceGit.sln --no-restore --configuration Release

    - name: 🧪 Run tests
      run: dotnet test QuoteMachineTests\QuoteMachineTests.csproj --verbosity normal
